name: 'Robot Framework Tests'
description: 'End to End test with Robot Framework'
inputs:
  browser:
    description: The browser in which robot framework will run the tests.
    required: true
    default: headlessfirefox
  username:
    description: The username which will be used for authentication.
    required: true
  password:
    description: The password which will be used for authentication.
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ${{ github.action_path }}/test.sh
      env:
        RFW_HOST: http://localhost:3000
        RFW_BROWSER: ${{ inputs.browser }}
        RFW_USERNAME: ${{ inputs.username }}
        RFW_PASSWORD: ${{ inputs.password }}