name: CI

on: [push, workflow_dispatch]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup

      - name: Install SARIF formatter
        run: yarn add @microsoft/eslint-formatter-sarif

      - name: Lint
        run: yarn lint --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
  
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install Dependencies
        run: yarn install --ignore-scripts --frozen-lockfile

      - name: Build
        run: yarn build
