name: Deploy Development

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

  deploy:
    needs: lint
    if: "!failure()"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup

      - name: Build
        run: yarn build
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          HUB_URL: ${{ vars.DEV_HUB_URL }}
          DEBUG: ${{ vars.DEBUG }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          BOARD_SAVE_INTERVAL: ${{ vars.DEV_BOARD_SAVE_INTERVAL }}
          GOOGLE_AUTH_CLIENT_ID: ${{ secrets.DEV_GOOGLE_AUTH_CLIENT_ID }}
          GITHUB_AUTH_CLIENT_ID: ${{ secrets.DEV_GITHUB_AUTH_CLIENT_ID }}

      - name: Bundle Build Artifacts
        run: cp -r functions dist/functions

      - name: Prepare Provisioning
        uses: cschleiden/replace-tokens@v1
        with:
          files: "wrangler.toml"
        env:
          GOOGLE_AUTH_CLIENT_ID: ${{ secrets.DEV_GOOGLE_AUTH_CLIENT_ID }}
          GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.DEV_GOOGLE_AUTH_CLIENT_SECRET }}
          GITHUB_AUTH_CLIENT_ID: ${{ secrets.DEV_GITHUB_AUTH_CLIENT_ID }}
          GITHUB_AUTH_CLIENT_SECRET: ${{ secrets.DEV_GITHUB_AUTH_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Publish Build to Cloudflare Pages
        run: npx wrangler pages publish dist --project-name greyboard --branch ${{ github.ref_name }} --commit-message ${{ github.sha }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Run Database Migrations
        run: npx wrangler d1 migrations apply greyboard-db-dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}